/**
 * Plugin Wrapper Generator for workerd
 *
 * Generates the code that wraps a plugin to run in a workerd isolate.
 * Unlike the Cloudflare wrapper which uses RPC via service bindings,
 * this wrapper uses HTTP fetch to call the Node backing service.
 *
 * The wrapper:
 * - Imports plugin hooks and routes from "sandbox-plugin.js"
 * - Creates plugin context that proxies operations via HTTP to the backing service
 * - Exposes an HTTP fetch handler for hook/route invocation
 */

import { Buffer } from "node:buffer";

import { normalizePluginCapabilities, type PluginManifest } from "emdash";
import { generatePluginHttpWireRuntimeSource } from "emdash/internal/plugins/http-wire";

const TRAILING_SLASH_RE = /\/$/;
const NEWLINE_RE = /[\n\r]/g;
const COMMENT_CLOSE_RE = /\*\//g;

const ROUTE_BYTES_MARKER = "__emdashBytes";
const ROUTE_ESCAPED_OBJECT_MARKER = "__emdashEscapedObject";

function isReservedRouteTransportObject(value: unknown): value is Record<string, unknown> {
	if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
	const keys = Object.keys(value);
	return (
		keys.length === 1 && (keys[0] === ROUTE_BYTES_MARKER || keys[0] === ROUTE_ESCAPED_OBJECT_MARKER)
	);
}

export function stringifyRouteTransport(value: unknown): string {
	return JSON.stringify(value, (_key, entry) => {
		if (entry instanceof Uint8Array) {
			return { [ROUTE_BYTES_MARKER]: Buffer.from(entry).toString("base64") };
		}
		if (isReservedRouteTransportObject(entry)) {
			return { [ROUTE_ESCAPED_OBJECT_MARKER]: Object.entries(entry) };
		}
		return entry;
	});
}

export function parseRouteTransport(value: string): unknown {
	return JSON.parse(value, (_key: string, entry: unknown) => {
		if (entry === null || typeof entry !== "object" || Array.isArray(entry)) return entry;
		const keys = Object.keys(entry);
		const bytes = Reflect.get(entry, ROUTE_BYTES_MARKER);
		if (keys.length === 1 && typeof bytes === "string") {
			return new Uint8Array(Buffer.from(bytes, "base64"));
		}
		const escaped = Reflect.get(entry, ROUTE_ESCAPED_OBJECT_MARKER);
		if (keys.length === 1 && Array.isArray(escaped)) {
			return Object.fromEntries(escaped);
		}
		return entry;
	});
}

export interface WrapperOptions {
	site?: {
		name: string;
		url: string;
		locale: string;
		trailingSlash?: "always" | "never" | "ignore";
	};
	/** URL of the Node backing service (e.g., http://127.0.0.1:18787) */
	backingServiceUrl: string;
	/** Auth token the plugin sends on outbound bridge calls to Node */
	authToken: string;
	/**
	 * Auth token the Node runner must send on inbound hook/route invocations.
	 * Prevents same-host attackers from invoking plugin hooks directly via
	 * the per-plugin TCP listener (which is exposed on 127.0.0.1).
	 */
	invokeToken: string;
}

export function generatePluginWrapper(manifest: PluginManifest, options: WrapperOptions): string {
	const site = options.site ?? { name: "", url: "", locale: "en" };
	const capabilities = normalizePluginCapabilities(manifest.capabilities);
	const hasContentAccess =
		capabilities.includes("content:read") ||
		capabilities.includes("content:write") ||
		capabilities.includes("content:revisions:read") ||
		capabilities.includes("content:publish") ||
		capabilities.includes("content:restore");
	const hasReadUsers = capabilities.includes("users:read");
	const hasEmailSend = capabilities.includes("email:send");
	const hasReadComments = capabilities.includes("comments:read");
	const hasModerateComments = capabilities.includes("comments:moderate");
	const hasRedirectRead = capabilities.includes("redirects:read");
	const hasRedirectWrite = capabilities.includes("redirects:write");
	const hasContentRead = capabilities.some((capability) =>
		["content:read", "content:write", "content:publish", "content:revisions:read"].includes(
			capability,
		),
	);
	const hasContentWrite = capabilities.includes("content:write");
	const hasContentPublish = capabilities.includes("content:publish");
	const hasContentRestore = capabilities.includes("content:restore");
	const hasSchemaRead = capabilities.includes("schema:read");
	const hasBylinesRead = capabilities.includes("bylines:read");
	const hasRevisionRead = capabilities.includes("content:revisions:read");
	const httpWireRuntimeSource = generatePluginHttpWireRuntimeSource();

	return `
// =============================================================================
// Sandboxed Plugin Wrapper (workerd)
// Generated by @emdash-cms/sandbox-workerd
// Plugin: ${sanitizeComment(manifest.id)}@${sanitizeComment(manifest.version)}
// =============================================================================

import pluginModule from "sandbox-plugin.js";

${httpWireRuntimeSource}

const hooks = pluginModule?.hooks || pluginModule?.default?.hooks || {};
const routes = pluginModule?.routes || pluginModule?.default?.routes || {};

const BACKING_URL = ${JSON.stringify(options.backingServiceUrl)};
const AUTH_TOKEN = ${JSON.stringify(options.authToken)};
const INVOKE_TOKEN = ${JSON.stringify(options.invokeToken)};

function routeTransportReplacer(_key, value) {
	if (value instanceof Uint8Array) {
		let binary = "";
		const chunkSize = 0x8000;
		for (let offset = 0; offset < value.byteLength; offset += chunkSize) {
			binary += String.fromCharCode(...value.subarray(offset, offset + chunkSize));
		}
		return { __emdashBytes: btoa(binary) };
	}
	if (value && typeof value === "object" && !Array.isArray(value)) {
		const keys = Object.keys(value);
		if (keys.length === 1 &&
			(keys[0] === "__emdashBytes" || keys[0] === "__emdashEscapedObject")) {
			return { __emdashEscapedObject: Object.entries(value) };
		}
	}
	return value;
}

function transportReviver(_key, value) {
	if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== 1) return value;
	if (typeof value.__emdashBytes === "string") {
		const binary = atob(value.__emdashBytes);
		const bytes = new Uint8Array(binary.length);
		for (let index = 0; index < binary.length; index++) bytes[index] = binary.charCodeAt(index);
		return bytes;
	}
	if (Array.isArray(value.__emdashEscapedObject)) {
		return Object.fromEntries(value.__emdashEscapedObject);
	}
	return value;
}

function routeJsonResponse(value) {
	return new Response(JSON.stringify(value, routeTransportReplacer), {
		headers: { "content-type": "application/json" },
	});
}

function storageObjectEntries(value) {
	if (!value || typeof value !== "object" || Array.isArray(value) ||
		(Object.getPrototypeOf(value) !== Object.prototype && Object.getPrototypeOf(value) !== null) ||
		Object.getOwnPropertySymbols(value).length) {
		throw new TypeError("Storage update objects must be plain objects");
	}
	return Object.entries(value);
}

function copyStorageCondition(value, ancestors = new Set()) {
	if (value === null || typeof value === "string" || typeof value === "boolean") return value;
	if (typeof value === "number" && Number.isFinite(value)) return value;
	if (typeof value !== "object" || ancestors.has(value)) {
		throw new TypeError("Storage conditions must contain finite JSON values without cycles");
	}
	ancestors.add(value);
	let copied;
	if (Array.isArray(value)) {
		if (Object.getPrototypeOf(value) !== Array.prototype ||
			Object.getOwnPropertySymbols(value).length ||
			Object.keys(value).length !== value.length) {
			throw new TypeError("Storage condition arrays must contain only indexed values");
		}
		copied = Array.from({ length: value.length }, (_, index) =>
			copyStorageCondition(value[index], ancestors));
	} else {
		copied = Object.fromEntries(storageObjectEntries(value).map(([key, entry]) =>
			[key, copyStorageCondition(entry, ancestors)]));
	}
	ancestors.delete(value);
	return copied;
}

function copyStorageWhere(value) {
	return Object.fromEntries(storageObjectEntries(value).map(([field, condition]) => {
		if (condition === null || typeof condition !== "object") {
			return [field, copyStorageCondition(condition)];
		}
		const filter = Object.fromEntries(storageObjectEntries(condition));
		if (Array.isArray(filter.in)) {
			return [field, { in: copyStorageCondition(filter.in) }];
		}
		if (typeof filter.startsWith === "string") {
			return [field, { startsWith: filter.startsWith }];
		}
		const bounds = ["gt", "gte", "lt", "lte"]
			.filter((key) => Object.hasOwn(filter, key))
			.map((key) => [key, filter[key]]);
		if (bounds.length === 0) return [field, copyStorageCondition(filter)];
		const defined = bounds.filter(([, bound]) => bound !== undefined);
		if (defined.length === 0) {
			throw new TypeError("Storage range filter must contain a defined bound");
		}
		return [field, copyStorageCondition(Object.fromEntries(defined))];
	}));
}

function marshalStorageUpdate(value) {
	const entries = storageObjectEntries(value).map(([key, entry]) =>
		[key, key === "set" || key === "delta" ? entry :
			key === "where" ? copyStorageWhere(entry) : copyStorageCondition(entry)]);
	return Object.fromEntries(entries.flatMap(([key, entry]) => {
		if (key !== "set" && key !== "delta") return [[key, entry]];
		if (entry === undefined) return [];
		const fields = storageObjectEntries(entry)
			.filter(([, fieldValue]) => fieldValue !== undefined)
			.map(([field, fieldValue]) => {
				if (key === "delta") return [field, copyStorageCondition(fieldValue)];
				const serialized = JSON.stringify(fieldValue);
				if (serialized === undefined) {
					throw new TypeError("Storage set values must be JSON serializable");
				}
				return [field, JSON.parse(serialized)];
			});
		return [[key, Object.fromEntries(fields)]];
	}));
}

function storageSerializationErrorDetails(value) {
	if (!value || typeof value !== "object" ||
		value.code !== "STORAGE_SERIALIZATION_FAILURE" || value.retryable !== true ||
		(value.sqlState !== undefined && value.sqlState !== "40001" && value.sqlState !== "40P01")) return null;
	return {
		name: "StorageSerializationError",
		code: "STORAGE_SERIALIZATION_FAILURE",
		retryable: true,
		...(value.sqlState === undefined ? {} : { sqlState: value.sqlState }),
		message: "Storage write must be retried. Restart the transaction before retrying when using an explicit transaction.",
	};
}

function contentCreateErrorDetails(value) {
	if (!value || typeof value !== "object") return null;
	const code = value.code;
	if (
		code !== "CONFLICT" &&
		code !== "NOT_FOUND" &&
		code !== "SAVE_REJECTED" &&
		code !== "VALIDATION_ERROR"
	) return null;
	return {
		name: code,
		code,
		message: typeof value.message === "string" ? value.message : "Content create failed"
	};
}

const SANDBOX_ROUTE_ERROR_MESSAGES = {
	MEDIA_USAGE_ACTIVATION_IN_PROGRESS: "Media usage activation is in progress",
	MEDIA_USAGE_ACTIVATION_CHECK_FAILED: "Unable to verify media usage activation state",
	TRANSFER_IMPORT_IN_PROGRESS: "A site import is in progress or incomplete; writes are disabled",
	TRANSFER_FENCE_CHECK_FAILED: "Unable to verify whether site writes are allowed",
};

function sandboxRouteErrorDetails(value) {
	if (!value || typeof value !== "object") return null;
	const code = Object.hasOwn(SANDBOX_ROUTE_ERROR_MESSAGES, value.code)
		? value.code
		: Object.hasOwn(SANDBOX_ROUTE_ERROR_MESSAGES, value.name)
			? value.name
			: null;
	if (!code || (value.status !== undefined && value.status !== 503)) return null;
	return { code, message: SANDBOX_ROUTE_ERROR_MESSAGES[code], status: 503 };
}

function commentErrorDetails(value) {
	if (!value || typeof value !== "object" ||
		(value.code !== "COMMENT_STATUS_CONFLICT" &&
			value.code !== "COMMENT_MODERATION_IN_PROGRESS" &&
			value.code !== "COMMENT_STATUS_INVALID") ||
		typeof value.message !== "string" ||
		(value.code === "COMMENT_STATUS_CONFLICT" && typeof value.currentStatus !== "string")) return null;
	return {
		code: value.code,
		message: value.message,
		...(typeof value.currentStatus === "string" ? { currentStatus: value.currentStatus } : {}),
	};
}

function sandboxRouteErrorResponse(error) {
	const details = sandboxRouteErrorDetails(error);
	return details
		? Response.json(
				{ __emdashSandboxRouteError: true, error: details },
				{ status: details.status },
			)
		: null;
}

async function unwrapRedirectResult(promise) {
	const result = await promise;
	if (result?.ok === true) return result.value;
	if (result?.ok === false && result.error && typeof result.error.code === "string") {
		throw Object.assign(new Error(result.error.message), {
			name: "RedirectAccessError",
			code: result.error.code,
		});
	}
	throw new Error("Invalid redirect bridge response");
}

// -----------------------------------------------------------------------------
// Bridge - HTTP calls to Node backing service
// -----------------------------------------------------------------------------

async function bridgeCall(method, body) {
	const res = await fetch(BACKING_URL + "/" + method, {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			"Authorization": "Bearer " + AUTH_TOKEN,
		},
		body: JSON.stringify(body),
	});
	if (!res.ok) {
		const text = await res.text();
		try {
			const payload = JSON.parse(text);
			const storageDetails = storageSerializationErrorDetails(payload?.error);
			if (storageDetails) throw Object.assign(new Error(storageDetails.message), storageDetails);
			const commentDetails = commentErrorDetails(payload?.error);
			if (commentDetails) {
				throw Object.assign(new Error(commentDetails.message), commentDetails, {
					name: commentDetails.code,
				});
			}
			const contentCreateDetails = contentCreateErrorDetails(payload?.error);
			if (contentCreateDetails) {
				throw Object.assign(new Error(contentCreateDetails.message), contentCreateDetails, { name: contentCreateDetails.code });
			}
			const details = sandboxRouteErrorDetails(payload?.error);
			if (details) {
				const error = Object.assign(new Error(details.message), details, {
					name: details.code,
				});
				throw error;
			}
		} catch (error) {
			if (
				sandboxRouteErrorDetails(error) ||
				storageSerializationErrorDetails(error) ||
				commentErrorDetails(error) ||
				contentCreateErrorDetails(error)
			) throw error;
		}
		throw new Error("Bridge call " + method + " failed: " + text);
	}
	const data = JSON.parse(await res.text(), transportReviver);
	return data.result;
}

// -----------------------------------------------------------------------------
// Context Factory
// -----------------------------------------------------------------------------

function createContext(originHook, invocationId) {
	const kv = {
		get: (key) => bridgeCall("kv/get", { key }),
		set: (key, value) => bridgeCall("kv/set", { key, value }),
		getVersioned: (key) => bridgeCall("kv/getVersioned", { key }),
		compareAndSet: (key, expectedRevision, value) => bridgeCall("kv/compareAndSet", { key, expectedRevision, value }),
		compareAndDelete: (key, expectedRevision) => bridgeCall("kv/compareAndDelete", { key, expectedRevision }),
		delete: (key) => bridgeCall("kv/delete", { key }),
		list: (prefix) => bridgeCall("kv/list", { prefix }),
	};

	const settings = {
		get: (key) => bridgeCall("settings/get", { key }),
		set: (key, value) => bridgeCall("settings/set", { key, value }),
		getVersioned: (key) => bridgeCall("settings/getVersioned", { key }),
		compareAndSet: (key, expectedRevision, value) => bridgeCall("settings/compareAndSet", { key, expectedRevision, value }),
		compareAndDelete: (key, expectedRevision) => bridgeCall("settings/compareAndDelete", { key, expectedRevision }),
		delete: (key) => bridgeCall("settings/delete", { key }),
		list: (prefix) => bridgeCall("settings/list", { prefix }),
	};

	function createStorageCollection(collectionName) {
		return {
			get: (id) => bridgeCall("storage/get", { collection: collectionName, id }),
			put: (id, data) => bridgeCall("storage/put", { collection: collectionName, id, data }),
			getVersioned: (id) => bridgeCall("storage/getVersioned", { collection: collectionName, id }),
			compareAndSet: (id, expectedRevision, data) => bridgeCall("storage/compareAndSet", { collection: collectionName, id, expectedRevision, data }),
			compareAndDelete: (id, expectedRevision) => bridgeCall("storage/compareAndDelete", { collection: collectionName, id, expectedRevision }),
			updateIf: async (id, args) => {
				if (typeof id !== "string") throw new TypeError("Storage ID must be a string");
				return bridgeCall("storage/updateIf", { collection: collectionName, id, args: marshalStorageUpdate(args) });
			},
			delete: (id) => bridgeCall("storage/delete", { collection: collectionName, id }),
			exists: async (id) => (await bridgeCall("storage/get", { collection: collectionName, id })) !== null,
			query: (opts) => bridgeCall("storage/query", { collection: collectionName, ...opts }),
			count: (where) => bridgeCall("storage/count", { collection: collectionName, where }),
			getMany: async (ids) => {
				// Bridge returns a list of [id, data] pairs (not a plain object)
				// so special IDs like "__proto__" survive transport. Convert
				// back to Map to match StorageCollection.getMany() contract.
				const entries = await bridgeCall("storage/getMany", { collection: collectionName, ids });
				return new Map(entries || []);
			},
			putMany: (items) => bridgeCall("storage/putMany", { collection: collectionName, items }),
			deleteMany: (ids) => bridgeCall("storage/deleteMany", { collection: collectionName, ids }),
		};
	}

	const storage = new Proxy({}, {
		get(_, collectionName) {
			if (typeof collectionName !== "string") return undefined;
			return createStorageCollection(collectionName);
		}
	});

	async function contentAction(promise) {
		const result = await promise;
		if (result && result.__emdashContentActionError === true && result.error) {
			throw Object.assign(new Error(result.error.message), result.error, { name: result.error.code });
		}
		return result;
	}

	const content = ${hasContentAccess} ? {
		get: (collection, id) => bridgeCall("content/get", { collection, id }),
		list: (collection, opts) => bridgeCall("content/list", { collection, ...opts }),
		...(${hasContentRead} ? {
			getTranslations: (collection, id) => bridgeCall("content/translations", { collection, id }),
			getPublicUrl: (collection, id) => bridgeCall("content/publicUrl", { collection, id }),
			...(${hasRevisionRead} ? {
				listRevisions: (collection, id, options) => bridgeCall("content/listRevisions", { collection, id, options }),
				getRevision: (collection, id, revisionId) => bridgeCall("content/getRevision", { collection, id, revisionId })
			} : {})
		} : {}),
		...(${hasContentWrite} ? {
			create: (collection, data, options) => bridgeCall("content/create", { collection, data, options, originHook }),
			update: (collection, id, data) => bridgeCall("content/update", { collection, id, data }),
			delete: (collection, id) => bridgeCall("content/delete", { collection, id }),
			createMany: (collection, items) => bridgeCall("content/createMany", { collection, items }),
			updateMany: (collection, items) => bridgeCall("content/updateMany", { collection, items }),
			deleteMany: (collection, ids) => bridgeCall("content/deleteMany", { collection, ids })
		} : {}),
		...(${hasContentPublish} ? {
			getVersioned: (collection, id) => contentAction(bridgeCall("content/getVersioned", { collection, id })),
			publish: (collection, id, options) => contentAction(bridgeCall("content/publish", { collection, id, revision: options._rev, invocationId })),
			unpublish: (collection, id, options) => contentAction(bridgeCall("content/unpublish", { collection, id, revision: options._rev, invocationId })),
			schedule: (collection, id, options) => contentAction(bridgeCall("content/schedule", { collection, id, scheduledAt: options.scheduledAt, revision: options._rev, invocationId })),
			unschedule: (collection, id, options) => contentAction(bridgeCall("content/unschedule", { collection, id, revision: options._rev, invocationId }))
		} : {}),
		...(${hasContentRestore} ? {
			getTrashedVersioned: (collection, id) => contentAction(bridgeCall("content/getTrashedVersioned", { collection, id })),
			restore: (collection, id, options) => contentAction(bridgeCall("content/restore", { collection, id, revision: options._rev, invocationId }))
		} : {})
	} : undefined;

	const schema = ${hasSchemaRead} ? {
		listCollections: () => bridgeCall("schema/listCollections", {}),
		getCollection: (slug) => bridgeCall("schema/getCollection", { slug })
	} : undefined;

	// Taxonomy access - capability enforced by the bridge
	const taxonomies = {
		getAll: (opts) => bridgeCall("taxonomy/list", { ...opts }),
		getTerms: (taxonomy, opts) => bridgeCall("taxonomy/terms", { taxonomy, ...opts }),
		getEntryTerms: (collection, entryId, opts) => bridgeCall("taxonomy/entryTerms", { collection, entryId, ...opts }),
		createTerm: (taxonomy, input) => bridgeCall("taxonomy/createTerm", { taxonomy, input }),
		addEntryTerms: (collection, entryId, taxonomy, termIds) => bridgeCall("taxonomy/addEntryTerms", { collection, entryId, taxonomy, termIds }),
		removeEntryTerms: (collection, entryId, taxonomy, termIds) => bridgeCall("taxonomy/removeEntryTerms", { collection, entryId, taxonomy, termIds }),
	};

	const bylines = ${hasBylinesRead} ? {
		get: (id) => bridgeCall("bylines/get", { id }),
		list: (opts) => bridgeCall("bylines/list", { ...opts }),
		getEntriesBylines: (collection, entryIds) => bridgeCall("bylines/entriesBylines", { collection, entryIds }),
	} : undefined;

	const redirects = ${hasRedirectRead} ? {
		list: (opts) => unwrapRedirectResult(bridgeCall("redirect/list", opts || {})),
		get: (id) => unwrapRedirectResult(bridgeCall("redirect/get", { id })),
		...(${hasRedirectWrite} ? {
			create: (input) => unwrapRedirectResult(bridgeCall("redirect/create", { input })),
			update: (id, input) => unwrapRedirectResult(bridgeCall("redirect/update", { id, input })),
			delete: (id, options) => unwrapRedirectResult(bridgeCall("redirect/delete", { id, revision: options?._rev })),
		} : {}),
	} : undefined;

	const media = {
		get: (id) => bridgeCall("media/get", { id }),
		list: (opts) => bridgeCall("media/list", opts || {}),
		readBytes: async (id, opts) => {
			const result = await bridgeCall("media/readBytes", { id, maxBytes: opts?.maxBytes });
			if (result?.encoding !== "base64" || typeof result.bytes !== "string") {
				throw new Error("Invalid media byte response");
			}
			const binary = atob(result.bytes);
			const bytes = new Uint8Array(binary.length);
			for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
			const { encoding: _encoding, ...media } = result;
			return { ...media, bytes };
		},
		updateMetadata: (id, patch) => bridgeCall("media/updateMetadata", { id, patch }),
		upload: (filename, contentType, bytes) => {
			// Convert any binary input into a Uint8Array view pointing at the
			// SAME underlying bytes (not reinterpreted). For ArrayBufferView
			// inputs (Uint16Array, Int32Array, DataView, etc.) we must use
			// the view's buffer + byteOffset + byteLength so we don't
			// reinterpret element-typed values as bytes and corrupt the file.
			let view;
			if (bytes instanceof Uint8Array) {
				view = bytes;
			} else if (bytes instanceof ArrayBuffer) {
				view = new Uint8Array(bytes);
			} else if (ArrayBuffer.isView(bytes)) {
				view = new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength);
			} else {
				throw new TypeError("media.upload: bytes must be ArrayBuffer or ArrayBufferView");
			}
			let binary = "";
			for (let i = 0; i < view.length; i++) binary += String.fromCharCode(view[i]);
			return bridgeCall("media/upload", {
				filename,
				contentType,
				bytes: btoa(binary),
				encoding: "base64",
			});
		},
		getUploadUrl: () => { throw new Error("getUploadUrl is not available in sandbox mode. Use media.upload() instead."); },
		delete: (id) => bridgeCall("media/delete", { id }),
	};

	// Marshal a RequestInit into a bounded JSON-safe shape. Request performs the
	// standard BodyInit encoding before the decoded bytes are measured.
	async function marshalRequestInit(init) {
		if (!init) return undefined;
		let body = init.body;
		const isBodyInit =
			typeof body === "string" ||
			body instanceof URLSearchParams ||
			body instanceof ArrayBuffer ||
			ArrayBuffer.isView(body) ||
			(typeof Blob !== "undefined" && body instanceof Blob) ||
			(typeof FormData !== "undefined" && body instanceof FormData) ||
			(typeof ReadableStream !== "undefined" && body instanceof ReadableStream);
		if (body !== undefined && body !== null && !isBodyInit) body = JSON.stringify(body);
		const buffered = await bufferPluginHttpRequest({ ...init, body });
		const out = {};
		if (buffered?.method) out.method = buffered.method;
		if (buffered?.redirect) out.redirect = buffered.redirect;
		const headers = Array.from(new Headers(buffered?.headers).entries());
		if (headers.length > 0) out.headers = headers;
		if (buffered?.body !== undefined && buffered.body !== null) {
			const bytes = new Uint8Array(buffered.body);
			let binary = "";
			for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
			out.bodyType = "base64";
			out.body = btoa(binary);
		}
		return out;
	}

	const http = {
		fetch: async (url, init) => {
			const marshaledInit = await marshalRequestInit(init);
			const result = await bridgeCall("http/fetch", { url, init: marshaledInit });
			return pluginHttpResponseFromWire(result);
		}
	};

	const log = {
		debug: (msg, data) => bridgeCall("log", { level: "debug", msg, data }),
		info: (msg, data) => bridgeCall("log", { level: "info", msg, data }),
		warn: (msg, data) => bridgeCall("log", { level: "warn", msg, data }),
		error: (msg, data) => bridgeCall("log", { level: "error", msg, data }),
	};

	const site = ${JSON.stringify(site)};
	const siteBaseUrl = ${JSON.stringify(site.url.replace(TRAILING_SLASH_RE, ""))};

	function url(path) {
		if (!path.startsWith("/")) {
			throw new Error('URL path must start with "/", got: "' + path + '"');
		}
		if (path.startsWith("//")) {
			throw new Error('URL path must not be protocol-relative, got: "' + path + '"');
		}
		return siteBaseUrl + path;
	}

	const users = ${hasReadUsers} ? {
		get: (id) => bridgeCall("users/get", { id }),
		getByEmail: (email) => bridgeCall("users/getByEmail", { email }),
		list: (opts) => bridgeCall("users/list", opts || {}),
	} : undefined;

	const comments = ${hasReadComments} ? {
		get: (id) => bridgeCall("comments/get", { id }),
		list: (opts) => bridgeCall("comments/list", opts || {}),
		count: (opts) => bridgeCall("comments/count", opts || {}),
		...(${hasModerateComments} ? {
			setStatus: (id, status, opts) => bridgeCall("comments/setStatus", {
				id,
				status,
				expectedStatus: opts.expectedStatus,
			})
		} : {})
	} : undefined;

	const email = ${hasEmailSend} ? {
		send: (message) => bridgeCall("email/send", { message }),
	} : undefined;

	const cron = {
		schedule: (name, opts) => bridgeCall("cron/schedule", { name, ...opts }),
		cancel: (name) => bridgeCall("cron/cancel", { name }),
		list: () => bridgeCall("cron/list", {}),
	};

	return {
		plugin: {
			id: ${JSON.stringify(manifest.id)},
			version: ${JSON.stringify(manifest.version || "0.0.0")},
		},
		storage,
		kv,
		settings,
		content: ${hasContentAccess} ? content : undefined,
		schema,
		taxonomies,
		bylines,
		redirects,
		media,
		http,
		log,
		site,
		url,
		users,
		comments,
		email,
		cron,
	};
}

// -----------------------------------------------------------------------------
// HTTP Handler (replaces WorkerEntrypoint for workerd-on-Node)
// -----------------------------------------------------------------------------

// Constant-time string comparison. workerd doesn't expose
// crypto.timingSafeEqual, so XOR char codes manually. Always processes
// the full length of the longer input to avoid early-exit timing leaks.
function constantTimeEqual(a, b) {
	let result = a.length === b.length ? 0 : 1;
	const len = Math.max(a.length, b.length);
	for (let i = 0; i < len; i++) {
		const ac = i < a.length ? a.charCodeAt(i) : 0;
		const bc = i < b.length ? b.charCodeAt(i) : 0;
		result |= ac ^ bc;
	}
	return result === 0;
}

export default {
	async fetch(request) {
		const url = new URL(request.url);

		// Authenticate the caller. The plugin's TCP listener is exposed on
		// 127.0.0.1, so any local process could otherwise invoke hooks/routes
		// directly. Only the Node runner has the per-startup invoke token.
		// Use constant-time comparison: workerd doesn't expose timingSafeEqual,
		// so we XOR character codes manually. Same length always required.
		const authHeader = request.headers.get("authorization") || "";
		const expected = "Bearer " + INVOKE_TOKEN;
		if (!constantTimeEqual(authHeader, expected)) {
			return new Response("Unauthorized", { status: 401 });
		}

		if (url.pathname === "/__ready") {
			return new Response("ok", { status: 200 });
		}

		// Hook invocation: POST /hook/{hookName}
		if (url.pathname.startsWith("/hook/")) {
			const hookName = url.pathname.slice(6); // Remove "/hook/"
			const { event, invocationId } = await request.json();
			const ctx = createContext(hookName, invocationId);

			const hookDef = hooks[hookName];
			if (!hookDef) {
				return Response.json({ value: undefined });
			}

			const handler = typeof hookDef === "function" ? hookDef : hookDef.handler;
			if (typeof handler !== "function") {
				return new Response("Hook " + hookName + " handler is not a function", { status: 500 });
			}

			try {
				const result = await handler(event, ctx);
				return Response.json({ value: result });
			} catch (err) {
				return new Response(err.message || "Hook error", { status: 500 });
			}
		}

		// Route invocation: POST /route/{routeName}
		if (url.pathname.startsWith("/route/")) {
			const routeName = url.pathname.slice(7); // Remove "/route/"
			const { input, request: serializedRequest, invocationId } = JSON.parse(
				await request.text(),
				transportReviver,
			);
			const ctx = createContext(undefined, invocationId);

			const route = routes[routeName];
			if (!route) {
				return new Response("Route not found: " + routeName, { status: 404 });
			}

			const handler = typeof route === "function" ? route : route.handler;
			if (typeof handler !== "function") {
				return new Response("Route " + routeName + " handler is not a function", { status: 500 });
			}

			try {
				// user: authenticated caller for private routes, resolved by
				// the host before dispatch.
				const result = await handler(
					{
						input,
						request: serializedRequest,
						requestMeta: serializedRequest?.meta,
						user: serializedRequest?.user,
						ui: serializedRequest?.ui,
					},
					ctx,
				);
				return routeJsonResponse(result);
			} catch (err) {
				const sandboxError = sandboxRouteErrorResponse(err);
				if (sandboxError) return sandboxError;
				return new Response(err.message || "Route error", { status: 500 });
			}
		}

		return new Response("Not found", { status: 404 });
	}
};
`;
}

function sanitizeComment(s: string): string {
	return s.replace(NEWLINE_RE, " ").replace(COMMENT_CLOSE_RE, "* /");
}
