/**
 * GET /_emdash/api/auth/oauth/[provider]
 *
 * Start OAuth flow - redirects to provider authorization URL
 */

import type { APIRoute } from "astro";

export const prerender = false;

import { createAuthorizationUrl, type OAuthConsumerConfig } from "@emdash-cms/auth";

import { getPublicOrigin } from "#api/public-url.js";
import { getOAuthConfig, resolveOAuthProviderEnv } from "#auth/oauth-provider-env.js";
import { createOAuthStateStore } from "#auth/oauth-state-store.js";

type ProviderName = "github" | "google";

const VALID_PROVIDERS = new Set<string>(["github", "google"]);

/** Invite tokens are base64url; clamp shape and length before persisting to state. */
const INVITE_TOKEN_REGEX = /^[A-Za-z0-9_-]{1,256}$/;

function isValidProvider(provider: string): provider is ProviderName {
	return VALID_PROVIDERS.has(provider);
}

export const GET: APIRoute = async ({ params, request, locals, redirect }) => {
	const { emdash } = locals;
	const provider = params.provider;

	// Determine where to redirect errors (setup wizard or login page)
	const referer = request.headers.get("referer") ?? "";
	const errorRedirectBase = referer.includes("/setup")
		? "/_emdash/admin/setup"
		: "/_emdash/admin/login";

	// Validate provider
	if (!provider || !isValidProvider(provider)) {
		return redirect(
			`${errorRedirectBase}?error=invalid_provider&message=${encodeURIComponent("Invalid OAuth provider")}`,
		);
	}

	if (!emdash?.db) {
		return redirect(
			`${errorRedirectBase}?error=server_error&message=${encodeURIComponent("Database not configured")}`,
		);
	}

	try {
		const url = new URL(request.url);

		// Cloudflare bindings come from the virtual module. Node deployments
		// additionally need process.env because container secrets are injected
		// after Vite has evaluated import.meta.env.
		// @ts-ignore - virtual module, generated by the Astro integration
		const { env: adapterEnv } = (await import("virtual:emdash/env")) as {
			env?: Record<string, unknown>;
		};
		const env = resolveOAuthProviderEnv(adapterEnv, import.meta.env);
		const providers = getOAuthConfig(env);

		if (!providers[provider]) {
			return redirect(
				`${errorRedirectBase}?error=provider_not_configured&message=${encodeURIComponent(`OAuth provider ${provider} is not configured. Set either EMDASH_OAUTH_${provider.toUpperCase()}_CLIENT_ID and EMDASH_OAUTH_${provider.toUpperCase()}_CLIENT_SECRET, or ${provider.toUpperCase()}_CLIENT_ID and ${provider.toUpperCase()}_CLIENT_SECRET.`)}`,
			);
		}

		const config: OAuthConsumerConfig = {
			baseUrl: `${getPublicOrigin(url, emdash?.config)}/_emdash`,
			providers,
		};

		const stateStore = createOAuthStateStore(emdash.db);

		// When the flow starts from an invite link, carry the invite token so the
		// callback can complete the invite for a matching, verified email. Validate
		// its shape/length first: this endpoint is unauthenticated, so we avoid
		// persisting arbitrary or oversized values into the short-lived state store.
		const rawInvite = url.searchParams.get("invite");
		const inviteToken = rawInvite && INVITE_TOKEN_REGEX.test(rawInvite) ? rawInvite : undefined;

		const { url: authUrl } = await createAuthorizationUrl(config, provider, stateStore, {
			inviteToken,
		});

		return redirect(authUrl);
	} catch (error) {
		console.error("OAuth initiation error:", error);
		return redirect(
			`${errorRedirectBase}?error=oauth_error&message=${encodeURIComponent("Failed to start OAuth flow. Please try again.")}`,
		);
	}
};
