import type { ToolbarLabels } from "../../src/visual-editing/toolbar.js";

export const GERMAN_TOOLBAR_LABELS: ToolbarLabels = {
	publish: "Veröffentlichen",
	publishing: "Wird veröffentlicht…",
	sessionExpired: "Die Bearbeitungssitzung ist abgelaufen.",
	refreshPage: "Seite neu laden",
	publishFailed: "Veröffentlichen fehlgeschlagen.",
	editMode: "Bearbeitungsmodus",
	openInAdmin: "Im Adminbereich öffnen",
	hideToolbar: "Symbolleiste ausblenden",
	draft: "Entwurf",
	published: "Veröffentlicht",
	unpublishedChanges: "Unveröffentlichte Änderungen",
	unsaved: "Nicht gespeichert",
	saving: "Wird gespeichert…",
	saved: "Gespeichert",
	saveFailed: "Speichern fehlgeschlagen",
	image: "Bild",
	noImageSelected: "Kein Bild ausgewählt",
	altText: "Alt-Text",
	altTextPlaceholder: "Beschreibe das Bild",
	replaceImage: "Ersetzen",
	uploadImage: "Hochladen",
	removeImage: "Entfernen",
	mediaLibrary: "Medienbibliothek",
	back: "Zurück",
	loading: "Wird geladen…",
	noImagesFound: "Keine Bilder gefunden",
	mediaLoadFailed: "Medien konnten nicht geladen werden",
	uploadingFile: "{filename} wird hochgeladen…",
};
